[package]
name = "cpuset"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }

